import { Lesson } from './lesson.model';

// include disclaimer "The days of the week are used to navigate you to the correct lessons and material. These may/will not match with the days you are pairing. Just trust us and follow along."

// include disclaimer "Review material is labeled with book icons and projects are labeled with pencil icons"

export const LESSON: Lesson[] = [
  new Lesson('beginner','HTML/CSS Intro', /*ok*/ 'https://www.learnhowtoprogram.com/intro-to-programming','https://www.learnhowtoprogram.com/intro-to-programming/git-html-and-css', 'You will be bettor off if you study the review material under "Pre-work" and "Getting Started with Intro to Programming" before code day. On code day start with the Week 1 "Git, HTML, and CSS" material starting with Mondays lesson, "Practice: Git Project Setup". If you make it through Mondays work, meetup again and start Tuesdays material, or continue on your own with Tuesdays work.'),
  new Lesson('beginner','CSS', /*ok*/ 'https://www.learnhowtoprogram.com/css','https://www.learnhowtoprogram.com/css/moving-forward-with-css', 'Begin by going through the review material labeled "Prework" and Week 1 "Weekend". Try and get as comfortable as you can with this material before code day. Hands on keys is the best way to learn! Type out that code! Then on code day start with the code day material beginning with "Top 8, Div playground, Landing pages" under Mondays material. If you make it through Mondays material continue to setup pair sessions and begin with Tuesdays material and so on!'),
  new Lesson('beginner','Javascript and JQuery', /*ok*/ 'https://www.learnhowtoprogram.com/intro-to-programming/javascript-and-jquery-c950c9ce-679c-4678-ab1f-11881b766e22','https://www.learnhowtoprogram.com/intro-to-programming/javascript-and-jquery-c950c9ce-679c-4678-ab1f-11881b766e22', 'If you havent gone through the "HTML/CSS Intro" lessons, it is suggested you do so. But if you are fairly comfortable with HTML and CSS then onward it is!! Review the material labeled "Weekend" under the "Intro to Programming / Javascript and JQuery". Its a lot but dont get intimidated! Try and get as comfortable as you can with this material before code day. Hands on keys is the best way to learn! Type out that code! Then on code day start with the code day material beginning with Mondays lesson titled "Functions". If you make it through Mondays material continue to setup pair sessions and begin with Tuesdays material and so on!'),
  new Lesson('beginner','Javascript and JQuery', /*revised*/ /*ok*/ 'https://www.learnhowtoprogram.com/intro-to-programming/arrays-looping/javascript-arrays-97974233-64a4-49d2-9bc6-a2128f7549cf','https://www.learnhowtoprogram.com/intro-to-programming/arrays-looping/practice-javascript-arrays-3d16150c-b8a3-4c7f-9e1c-4b15ea5f9cae', 'Begin by going through the review material on Arrays and Looping / JavaScript Arrays. Try and get as comfortable as you can with this material before code day. Hands on keys is the best way to learn! Type out that code! Then on code day start with the code day material beginning with a review of the Goal and Warm Up Section, then move onto a "Favorite Things Webpage."'),
  new Lesson('intermediate','JavaScript', /*ok*/ 'https://www.learnhowtoprogram.com/javascript','https://www.learnhowtoprogram.com/javascript/bdd-with-javascript', 'Begin by going through the review material labeled "Pre-Work" under the JavaScript course. Try and get as comfortable as you can with this material before code day. Hands on keys is the best way to learn! Type out that code! Then on code day start with the code day material beginning with "Practice with Gulp and npm" under Week 1 for Monday. If you make it through Mondays material continue to meetup and begin with Tuesdays material and so on!'),
  new Lesson('intermediate','JavaScript', /*ok*/ 'https://www.learnhowtoprogram.com/javascript/asynchrony-and-apis-in-javascript','https://www.learnhowtoprogram.com/javascript/asynchrony-and-apis-in-javascript/tamagotchi-animal-farm-pandemic-clone-timed-flashcards-two-day-projects', 'Begin by going through the review material labeled "Weekend" for "Asynchrony and APIs in JavaScript". Try and get as comfortable as you can with this material before code day. Hands on keys is the best way to learn! Type out that code! Then on code day start with the code day material beginning with "Tamagotchi, Animal Farm, Pandemic Clone, Timed Flashcards (Two-Day Projects)" under Mondays material. If you make it through Mondays material continue to meetup and begin with Tuesdays material and so on!'),
  new Lesson('intermediate','JavaScript/Angular', /*ok*/ 'https://www.learnhowtoprogram.com/javascript/angular','https://www.learnhowtoprogram.com/javascript/angular', 'Begin by going through the review material labeled "Weekend" for "JavaScript / Angular". Try and get as comfortable as you can with this material before code day. Hands on keys is the best way to learn! Type out that code! Then on code day start with the code day material beginning with "TypeScript Practice and Intro to Angular 2" under Mondays material. If you make it through Mondays material continue to meetup and begin with Tuesdays material and so on!'),
  new Lesson('intermediate','JavaScript/Angular', /*ok*/ 'https://www.learnhowtoprogram.com/javascript/angular','https://www.learnhowtoprogram.com/javascript/angular', 'Begin by going through the review material starting at and labeled Monday "Modern JavaScript MVCs" for "JavaScript / Angular". Try and get as comfortable as you can with this material before code day. Hands on keys is the best way to learn! Type out that code! Then on code day start with the code day material beginning with "To Do, Recipe Box" under Tuesdays material. If you make it through the material continue to meetup and begin with Wednesdays review material and so on!'),
  new Lesson('Intermediate','JavaScript/Angular', /*ok*/ 'https://www.learnhowtoprogram.com/javascript/angular-extendedhttps://www.learnhowtoprogram.com/javascript/angular-extended','https://www.learnhowtoprogram.com/javascript/angular-extended', 'Begin by going through the review material labeled "Weekend" for "JavaScript / Angular Extended". Try and get as comfortable as you can with this material before code day. Hands on keys is the best way to learn! Type out that code! Then on code day start with the code day material beginning with "Online Store, Discussion Forum, Craigslist" under Mondays material. If you make it through the Monday material continue to meetup and begin with Tuesdays review material and so on!'),
  new Lesson('intermediate','Java', /*ok*/ 'https://www.learnhowtoprogram.com/java','https://www.learnhowtoprogram.com/java/behavior-driven-development-with-java-08f0bd25-3437-4773-9191-207a7dbfb460', 'Begin by going through the review material labeled "Prework" for the "Java" course. Try and get as comfortable as you can with this material before code day. Hands on keys is the best way to learn! Type out that code! Then on code day start with the code day material beginning with "Dealership, Triangle Tracker, CD Store, and Parcels" under Mondays material. If you make it through the material continue to meetup and begin with Tuesdays review material and so on!'),
  new Lesson('intermediate','Java', /*ok*/ 'https://www.learnhowtoprogram.com/java/behavior-driven-development-with-java-08f0bd25-3437-4773-9191-207a7dbfb460','https://www.learnhowtoprogram.com/java/behavior-driven-development-with-java-08f0bd25-3437-4773-9191-207a7dbfb460', 'Begin by going through the review material starting at and labeled "Monday" for the "Java / Behavior Driven Development with Java" course. You should also be comfortable with the "Pre-work" under the "Java" course. Try and get as comfortable as you can with this material before code day. Hands on keys is the best way to learn! Type out that code! Then on code day start with the code day material beginning with "Scrabble Scorer, Rock-Paper-Scissors, Anagrams, and Prime Sifting" under Tuesdays material. If you make it through the material continue to meetup and begin with Tuesdays review material and so on!'),
  new Lesson('Advanced','JavaScript/Angular',  /*ok*/ 'https://www.learnhowtoprogram.com/javascript/angular-extended','https://www.learnhowtoprogram.com/javascript/angular-extended/online-store-choose-your-own-adventure', 'You should be comfortable with the material under the "Angular Extended" section in JavaScript. (Weekend and Mon, Tues) If you are not comfortable with the "Angular Extended" material you may want to choose one of the intermediate lessons. If you are comfortable then this lesson should be a challenge but should not be too challenging. On code day start with the code day material beginning with "Online Store, Choose Your Own Adventure" under Tuesdays material. If you make it through the material continue to meetup and choose another lesson!'),
  new Lesson('Intermediate','Java', /*ok*/ 'https://www.learnhowtoprogram.com/java/database-basics-b0d1a19d-8616-4092-90ca-60fbe2a49940','https://www.learnhowtoprogram.com/java/database-basics-b0d1a19d-8616-4092-90ca-60fbe2a49940', 'Begin by going through the review material labeled "Weekend" for the "Java / Database Basics" course. Try and get as comfortable as you can with this material before code day. Hands on keys is the best way to learn! Type out that code! Then on code day start with the code day material beginning with "SQL and Schema Practice, To Do, Address Book" under Mondays material. If you make it through Mondays material continue to meetup and begin with Tuesdays "Animal Shelter, Game of Choice" project and review material and so on!')

]
